"""re;late users to book

Revision ID: 0eef25fd5d9f
Revises: 8d07e01e2950
Create Date: 2026-04-11 00:42:50.186706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel         #####


# revision identifiers, used by Alembic.
revision: str = '0eef25fd5d9f'
down_revision: Union[str, Sequence[str], None] = '8d07e01e2950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('user_uid', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'book', 'users', ['user_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_column('book', 'user_uid')
    # ### end Alembic commands ###
