"""add hashed_password

Revision ID: 30fd2549b6ad
Revises: ced1cda36d2e
Create Date: 2026-04-06 00:59:30.744943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel         #####


# revision identifiers, used by Alembic.
revision: str = '30fd2549b6ad'
down_revision: Union[str, Sequence[str], None] = 'ced1cda36d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
