"""add roles to users

Revision ID: 8d07e01e2950
Revises: 30fd2549b6ad
Create Date: 2026-04-09 02:16:56.378352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel         #####


# revision identifiers, used by Alembic.
revision: str = '8d07e01e2950'
down_revision: Union[str, Sequence[str], None] = '30fd2549b6ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='user'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
