"""add passward hash

Revision ID: ced1cda36d2e
Revises: 294ee500c65c
Create Date: 2026-04-05 23:24:10.455358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel         #####


# revision identifiers, used by Alembic.
revision: str = 'ced1cda36d2e'
down_revision: Union[str, Sequence[str], None] = '294ee500c65c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
